learning_log/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls',namespace = 'users')),
    ]

learning_logs/urls.py
from django.urls import path
from . import views 
app_name = "learning_logs"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('topics/', views.topics, name = 'topics' ),
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    path('new_topic/', views.new_topic, name = 'new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry'),

]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text
    
class Entry(models.Model):
    topic = models.ForeignKey("Topic", on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

class Meta:
    vebose_name_plural = 'entries'
def __str__(self):
    char = len(list((self.text.split())))
    if char >=50:
        return self.text[:50] + "..."
    else:
        return self.text


                                 

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model =  Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'cols':80})}
        

learning_logs/views.py
from django.shortcuts import render, redirect, get_list_or_404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm



# Create your views here.
def topic(request,topic_id):
    topic = Topic.objects.get(id = topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic' : topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html',context)

def topics(request):
    topics = Topic.objects.order_by('date_added')
    
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html',context)

def index(request):
    return render(request, 'learning_logs/index.html')

def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    if request.method !=  'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

def edit_entry(request, entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance = entry)
    else:
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic')
    context = {'entry':entry , 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<p>
<a href="{% url 'learning_logs:index' %}">Díario Virtual</a> - <a href="{% url 'learning_logs:topics' %}">Tópicos</a> </p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Edit entry:</p>
    <form action = "{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <h1>Main page</h1>
    <p>Diário virtual ajuda você a continuar aprendendo e a resgistrar seus aprendizados.</p> 
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p> 
    <form action = "{% url 'learning_logs:new_entry' topic.id %}" method='post'> 
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button> 
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Add a new topic:</p>
    <form action="{% url 'learning_logs:new_topic' %}" method='post'> 
        {%csrf_token %}
        {{ form.as_p }}
        <button name="submit" >Add topic</button> 
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Tópico : {{topic}}</p>
    <p>Entradas:</p>
    <p> <a href="{% url 'learning_logs:new_entry' topic.id%}">add new entry</a> </p>
    <ul>
        {%for entry in entries%}
        <li>

            <p>{{entry.date_added|date:'d M, Y H:i'}}</p>
            <p>{{entry.text|linebreaks}}</p>
            <p><a href = "{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></p>

        </li>
        {%empty%}
            <li> Não a entradas para esse tópico ainda.</li>
        {%endfor%}
    </ul>


{%endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <h1>Topics</h1>

    <ul>{% for topic in topics %}

        <li> <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
        

        {%empty%}
            <li>Nenhum tópico foi adicionado ainda</li>
        {%endfor%}

    <ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>

{% endblock content %}